### ISSUE TITLE
Price editing problem - inconsistent formats causing trouble

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/mtesitoo-android#101]
Some requests accept or return prices as floats.
Other requests accept or return prices as formatted strings, including the currency symbol.

Unfortunately these are a bit mixed up.

This means that if you edit a product, you see eg. "D3".
If you change it to "D4", a crash happens. Only if you edit to a numeric value, and then save, are you able to successfully edit the product.

The most straightforward solution is to make all requests use floats, with no currency symbol included.

This will require testing and/or changes on both client and server.

**Comment by ptyagicodecamp** [comment]
implemented and deployed.
