### ISSUE TITLE
new photo added as auxiliary photo, not primary photo

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/mtesitoo-android#106]
1. log in
2. add a new product, with no photos
3. open the product
4. edit
5. add a new photo from the camera
6. click done

=> I expect the first photo to be added as the primary product photo

What actually happens is that the photo is added as an auxiliary product photo, and the primary product photo is left blank.

Tested on deployed Play Store app on Moto G3 / 5.1.

**Comment by ptyagicodecamp** [comment]
should be fixed now in play store/master branch.
