### ISSUE TITLE
product listing still showing image after deleting the image

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/mtesitoo-android#108]
1. Create a product with multiple images
2. Delete one of them (maybe has to be an auxiliary one?)
3. Click done.

Expected result: the product will now not show the deleted image.

=> Actual result: the product still shows all the original images

The image does appear to be deleted correctly on the server, however.

Tested on deployed Play Store app, Moto G3 / 5.1

**Comment by ptyagicodecamp** [comment]
should be fixed now in play store/master branch.
