### ISSUE TITLE
In product photo edit mode, images auto-slide when the dialog is showing

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/mtesitoo-android#109]
1. Create a product
2. Add several images
3. From product list, open product
4. Edit product
5. Click on photo
=> so that the add/delete photo dialog is showing
6. Wait 10 seconds (or however long it is)

Expected: the dialog remains showing over the image we first viewed.

=> Actual: the photos carry on sliding. If the photo slides on to the next one, will I delete the currently visible one, or the originally selected one.

**Perhaps we actually don't want to have sliding images at all on the edit screen?** A grid of product images would be a lot more appropriate, as well as giving a **much-needed visual cue to the user that we're looking at the edit screen, not the product details screen**.

Tested on app deployed to Play Store. Moto G3 / 5.1.

**Comment by ptyagicodecamp** [comment]
should be fixed now in play store/master branch.
