### ISSUE TITLE
Add Contact page, with item in menu

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/mtesitoo-android#111]
It's not clear how a vendor using the app can contact admin.
Just email address, phone number may be sufficient for now.
We should have an entry in the menu for that.

**Comment by ptyagicodecamp** [comment]
fixed in PR: https://github.com/projectwife/mtesitoo-android/pull/130

**Comment by ptyagicodecamp** [comment]
fix deployed to play store (vercode- 8).
