### ISSUE TITLE
Add missing fields: status, quantity, expiration date to product list screen

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/mtesitoo-android#113]
Our product list seems targeted towards a buyer, rather than a seller.
Vendor wants to see at a glance:
 • product name
 • price
 • quantity remaining (in red if it's low or none)
 • status (enabled / disabled / pending approval) (in red if it's not enabled)
 • expiration date (in red if it's past)
 • space for future enhancements (eg. show number of orders pending for product, or to flag up if no images have been uploaded, description is empty etc.)

Optionally, the category field could be removed, as it's more useful for buyer browsing, and will be shown on the product details screen.

**Comment by ptyagicodecamp** [comment]
[Current State of the code]: I see support for price and expiration date only at client side. However, expiration date formatting quite a bit messed up. Support for Qty remaining and Status needs to be added (I guess this is order status (?)) 

@david-r-edgar : Fyi

**Comment by ptyagicodecamp** [comment]
Price, exp date, quantity and status fields are implemented. updates are available in Play store build.

**Comment by gwenpowers** [comment]
Tested.  Works
