### ISSUE TITLE
Open product details on click on image in product list

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/mtesitoo-android#114]
In the product list, I have to click on a very small 'See details' link to open the product. Why not have the product details open when I click on the image? (Or even anywhere else on the listing, whatever works best.)

**Comment by gwenpowers** [comment]
This seems to be working as you suggested.  Item details open when image is clicked, but small 'See Details" now does nothing.

**Comment by david-r-edgar** [comment]
We should probably just remove the "See Details" now, then. Simpler is better.

**Comment by ptyagicodecamp** [comment]
Yes, "see details" is being disabled. UI changes to remove this widget are
in my local branch. Will commit them once I'm back home later this week.

Priyanka Tyagi | about.me/priyankatyagi

**Comment by ptyagicodecamp** [comment]
Fix available in Play store build now.
