### ISSUE TITLE
Missing 'expiration_date' field in Product's server response (?)

### ISSUE THREAD

**Issue by ptyagicodecamp** [projectwife/mtesitoo-android#121]
I don't see `expiration_date` being returned from server anymore. Is it intentional ?
Here's sample json:
[{"product_id":"208","name":"book","description":"book","price":0,"minimum":1,"quantity":1,"status":1,"thumb_image":"https://tesitoo.com/image/cache/catalog/prityainbox@gmail.com/mtesitoo_thumb_54607_1500187714-228x228.jpg","location":"","categories":["65"]},{"product_id":"189","name":"test2","description":"test2","price":0,"minimum":1,"quantity":100,"status":1,"thumb_image":"https://tesitoo.com/image/cache/catalog/prityainbox@gmail.com/mtesitoo_thumb_52067_1496689981-228x228.jpg","location":"","categories":["62"]},{"product_id":"200","name":"testthumb","description":"test ","price":0,"minimum":1,"quantity":1,"status":1,"thumb_image":"https://tesitoo.com/image/cache/catalog/prityainbox@gmail.com/mtesitoo_thumb_1674347898_1496349274-228x228.jpg","location":"","categories":["66"]},{"product_id":"190","name":"tree","description":"tree","price":0,"minimum":1,"quantity":100,"status":1,"thumb_image":"https://tesitoo.com/image/cache/catalog/prityainbox@gmail.com/mtesitoo_thumb_44694_1494446691-228x228.jpg","location":"","categories":["59"]}]

**Comment by ptyagicodecamp** [comment]
@david-r-edgar any insights ?

**Comment by david-r-edgar** [comment]
which request are you making?

**Comment by ptyagicodecamp** [comment]
Its getProducts: https://tesitoo.com/api/v1//vendor/products

**Comment by david-r-edgar** [comment]
Was it there before?

It's there for `GET /product/product/{id}`

I don't remember whether I added it for the multiple product list one. (If not, then I can, but it would be interesting to know whether this is actually a regression.)

**Comment by ptyagicodecamp** [comment]
I guess multiple products query was never tested before for exp_date :) I might be referring to `GET /product/product/{id}` because I remember seeing fixing `expiration_date` parsing before.

**Comment by ptyagicodecamp** [comment]
yes, please add `expiration_date` for multiple product query as well. We would need to show exp date in Product listing page.

**Comment by david-r-edgar** [comment]
Yes, I probably never added it to the multiple products. I'll do it later today, it should be quick. Are all the other fields needed for the product listing screen already there?

**Comment by ptyagicodecamp** [comment]
I think so. I'm sure about 'Price' and 'exp_date'. I think 'quantity' will map to 'qty remaining', and status mapping is: 0 - disabled, 1 - enabled....right ?

**Comment by david-r-edgar** [comment]
Yes - but also:
5 - pending approval

**Comment by ptyagicodecamp** [comment]
So, we've 0 (disabled), 1 (enabled) and 5 (pending approval) ? (wondering what are 2 thru 4 numbers meant)

**Comment by david-r-edgar** [comment]
They don't mean anything!
I don't remember why (if I ever knew).

**Comment by david-r-edgar** [comment]
But it's probably safest to say anything else should be treated as disabled. (There's nothing like that in the db at the moment.)

**Comment by ptyagicodecamp** [comment]
👍

**Comment by david-r-edgar** [comment]
Expiration date added to `GET /vendor/products` in #208.
