### ISSUE TITLE
'Add' button should not be shown on every screen

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/mtesitoo-android#13]
It's very confusing to see 'Add' in the top right corner when we're looking at a list of orders, or when we're looking at the user profile (for example). It should be removed in these and other similar cases.

It should still be shown on the home screen, and it should be shown on the list of products screen.

**Comment by carlpoole** [comment]
Todo: Remove Add button from Orders, Profile, Info, Help screens. (Check the inheritance of the top bar across these pages. Probably an issue with the fragment handling

**Comment by kaizen10** [comment]
The Add Product button should only be shown on the ProductFragment rather than the main activity.
