### ISSUE TITLE
App showing non-updated list of regions

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/mtesitoo-android#149]
The app is showing a list of regions (on the edit profile screen) which is incorrect.

It looks like it's an old static list.

Instead, it should show the list of regions returned by `GET /common/country/79` (as 79 == Gambia), as stored in the database.

Also, the text should just say 'Region' rather than 'Region/State'.

**Comment by edu11** [comment]
Currently the app make this request you mentioned and caches the data in a static list for next access as you said. Should the app always request regions from the server?

**Comment by david-r-edgar** [comment]
It wouldn't be a problem if it were cached for a while (eg. 1 hour or even 1 day).
But I updated this list on the server weeks and weeks ago... It definitely should have updated by now.

**Comment by david-r-edgar** [comment]
But if it's easiest, just request every time instead - because most probably the user won't be updating their profile all that often anyway, and it's not a particularly heavy request.

**Comment by edu11** [comment]
I will have a look at the options, even though is not a heavy request it'd be nice if we could cache it
