### ISSUE TITLE
long 'description' values aren't well handled

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/mtesitoo-android#22]
On the add product screen, could the input line for 'description' be a multi-line box instead?

On the product details screen, label 'Description' is written over the top of the start of the description (when one of ~15 words is set), obscuring both.

**Comment by carlpoole** [comment]
Just wanted to confirm, this is on Android yes? Or web

**Comment by carlpoole** [comment]
Will modify the screen layout to make sure labels and values dont clash
