### ISSUE TITLE
New user registration - Zone

### ISSUE THREAD

**Issue by JimPiquant** [projectwife/mtesitoo-android#24]
When registering as a new user and you choose a country with no zones, you get an empty screen instead of skipping. Low priority.

**Comment by carlpoole** [comment]
Pushed a quick fix for this in [#31](https://github.com/projectwife/mtesitoo-android/pull/31) that should address this by skipping the zone page. Still need to run a quick to test to make sure no crashes where the app is expecting a value for zone, etc.

**Comment by carlpoole** [comment]
I think I have this working now. @david-r-edgar is it okay if I submit zone 0 for countries that dont have any zones? Just wanted to make sure this wouldn't cause an error in the API if it tried to lookup the 0th item in an empty array or something. If not, what should I submit as the zone id for a country that doesnt have any?

**Comment by david-r-edgar** [comment]
I think that should be fine.
I put in a check that the zone has to be an integer, but there's no check that it matches the country.

(From what I've seen, if no zone (or an incorrect zone) is set, OpenCart (eg. in the admin screens) lists the zone as being the first valid one of the configured country. So it shouldn't cause anything to break.)

**Comment by carlpoole** [comment]
Fixed
