### ISSUE TITLE
New User Registration Fails

### ISSUE THREAD

**Issue by JimPiquant** [projectwife/mtesitoo-android#25]
When submitting a new user registration I get a failure:

D/Registration: Username: JimPiquant
E/Volley: [262] BasicNetwork.performRequest: Unexpected response code 400 for http://104.155.84.193/api/v1/vendor/register
W/EGL_emulation: eglSurfaceAttrib not implemented
W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x9eca8160, error=EGL_SUCCESS

**Comment by JimPiquant** [comment]
Tried to reproduce with a different country and it hangs.

**Comment by david-r-edgar** [comment]
The content being sent (captured with wireshark) looks like: 

`address_2=cssh&address_1=dhh&username=jo&telephone=554&city=fyh&email=jo&lastname=jo&firstname=jo&company=Company&postcode=password&country_id=123&`

The error being returned is:

`<b>Notice</b>: Undefined index: password in <b>/var/www/api/v1/catalog/controller/vendor/register.php</b> on line <b>20</b><b>Notice</b>: Undefined index: zone_id in <b>/var/www/api/v1/catalog/controller/vendor/register.php</b> on line <b>30</b><b>Notice</b>: Undefined index: password in <b>/var/www/api/v1/catalog/controller/vendor/register.php</b> on line <b>35</b><b>Notice</b>: Undefined index: zone_id in <b>/var/www/vqmod/vqcache/vq2-catalog_controller_account_signup.php</b> on line <b>674</b><b>Notice</b>: Undefined index: password in <b>/var/www/vqmod/vqcache/vq2-catalog_controller_account_signup.php</b> on line <b>678</b><b>Notice</b>: Undefined index: password in <b>/var/www/vqmod/vqcache/vq2-catalog_controller_account_signup.php</b> on line <b>682</b>{"errors":[{"code":"parameter_error","message":"Warning: You must agree to the Privacy Policy!"}]}`

So it appears that for some reason, a number of the fields are not being set at all (`password`, `zone_id` and `agree`).

In addition, 'password' is being set as the value for the postcode, which is incorrect (as it's what I typed in for the password field).

**Comment by david-r-edgar** [comment]
This corresponds with what we see in the console:

`I/System.out: mUsername jo`
`I/System.out: mFirstName jo`
`I/System.out: mLastName jo`
`I/System.out: mPhoneNumber 554`
`I/System.out: mEmail jo`
`I/System.out: mCompany Company`
`I/System.out: mAddress1 dhh`
`I/System.out: mAddress2 cssh`
`I/System.out: mCity fyh`
`I/System.out: mState uri`
`I/System.out: mPostcode password`
`I/System.out: mCountry 123`
`I/System.out: mDescription 1`
`I/System.out: mThumbnail 5`
`I/System.out: seller--Seller{mId=0, mUsername='jo', mFirstName='jo', mLastName='jo', mPhoneNumber='554', mEmail='jo', mCompany='Company', mCity='fyh', mPostcode='password', mThumbnail=5, mPassword='null', mZoneId='null', mAgree='null', mCountry='123'}`
`D/Registration: Registering Seller: Seller{mId=0, mUsername='jo', mFirstName='jo', mLastName='jo', mPhoneNumber='554', mEmail='jo', mCompany='Company', mCity='fyh', mPostcode='password', mThumbnail=5, mPassword='null', mZoneId='null', mAgree='null', mCountry='123'}`

**Comment by david-r-edgar** [comment]
#31 should fix this.

**Comment by carlpoole** [comment]
Tested with [#31](https://github.com/projectwife/mtesitoo-android/pull/31) but got a 400 error. Do you see what it was

`10-15 13:30:42.308 2702-2702/com.mtesitoo D/Registration: Registering Seller: Seller{mId=0, mUsername='carlpooletest1', mFirstName='Carl', mLastName='Poole', mPhoneNumber='1234567890', mEmail='mail@carlpoole.com', mCompany='Company', mCity='testCity', mPostcode='Z12345', mThumbnail=uri, mPassword='password123', mZoneId='49', mAgree='1', mCountry='2'}
10-15 13:30:42.308 2702-2702/com.mtesitoo D/mAuthorizationCache: CeU0ZvNL9zt4NtJCoGYeaiI8gQMY2jlt2hIidwTZ
10-15 13:30:42.316 2702-3210/com.mtesitoo D/Registration: Username: carlpooletest1
10-15 13:30:42.577 2702-3210/com.mtesitoo E/Volley: [180] BasicNetwork.performRequest: Unexpected response code 400 for http://104.155.84.193/api/v1/vendor/register`

**Comment by david-r-edgar** [comment]
Yes - if you look at the body of that 400 response, you'll see it says:
```
{
  "errors": [
    {
      "code": "parameter_error",
      "message": "Warning: E-Mail Address is already registered!"
    }
  ]
}
```
The email address is already in the oc_user table (entry added 2016-07-03 18:34:26).

So an error response is expected behaviour in this case.

**Comment by carlpoole** [comment]
Thanks David! I noticed we weren't parsing the bodies of errors from the server so I fixed that and we now show the actual error from the server in the app so users will know whats going on. I tested and it works well. Thanks for helping with the fix.
