### ISSUE TITLE
Edit Product

### ISSUE THREAD

**Issue by JimPiquant** [projectwife/mtesitoo-android#27]
Changes are not saved when I edit a product, including location and category

**Comment by carlpoole** [comment]
Related to https://trello.com/c/pBkeO9tu/83-mobile-edit-product - will review ASAP and resolve

**Comment by carlpoole** [comment]
Saving to the server isnt implemented in the app upon completion of edit product. Implementing...

**Comment by carlpoole** [comment]
Implemented this fix. Changes will be saved. Category and Location and SI Unit are separate issues potentially with API. Coordinating with david. See https://github.com/projectwife/mtesitoo-android/issues/28
