### ISSUE TITLE
Category missing on home screen and edit product

### ISSUE THREAD

**Issue by JimPiquant** [projectwife/mtesitoo-android#28]
Category assigned to a new item does not show on the home screen list, or when you view a product's details.  Changing the value in Edit Product does not update the field.

**Comment by david-r-edgar** [comment]
Looking at the admin screens, we see that the correct category has been set (i.e. in the database). So presumably retrieval of this category has not been correctly performed.

**Comment by carlpoole** [comment]
Hi david I don't think we have this being sent by the API. I noticed "Location" and "Category" were hardcoded in the product response in android and I checked the response from the API and it looks like it is absent. Can you confirm? Cheers

`


{"product":{"product_id":79,"title":"Magic Beans","model":"beans","description":"I'm not sure what they do","thumb_image":"http://tesitoo.com/image/cache/catalog/carlpoole/magic-beans-400x400.jpg","image":"http://tesitoo.com/image/cache/catalog/carlpoole/magic-beans-500x500.jpg","images":[{"thumb_image":"http://tesitoo.com/image/cache/catalog/carlpoole/magic-beans-74x74.jpg","image":"http://tesitoo.com/image/cache/catalog/carlpoole/magic-beans-500x500.jpg"},{"thumb_image":"http://tesitoo.com/image/cache/catalog/carlpoole/mtesitoo_20161002_140953-247241279_1475431874-74x74.jpg","image":"http://tesitoo.com/image/cache/catalog/carlpoole/mtesitoo_20161002_140953-247241279_1475431874-500x500.jpg"},{"thumb_image":"http://tesitoo.com/image/cache/catalog/carlpoole/mtesitoo_20161002_120420-2112746477_1475424270-74x74.jpg","image":"http://tesitoo.com/image/cache/catalog/carlpoole/mtesitoo_20161002_120420-2112746477_1475424270-500x500.jpg"},{"thumb_image":"http://tesitoo.com/image/cache/catalog/carlpoole/mtesitoo_20160925_144501-1498836048_1474829112-74x74.jpg","image":"http://tesitoo.com/image/cache/catalog/carlpoole/mtesitoo_20160925_144501-1498836048_1474829112-500x500.jpg"},{"thumb_image":"http://tesitoo.com/image/cache/catalog/carlpoole/mtesitoo_20161002_115740-523142368_1475423875-74x74.jpg","image":"http://tesitoo.com/image/cache/catalog/carlpoole/mtesitoo_20161002_115740-523142368_1475423875-500x500.jpg"},{"thumb_image":"http://tesitoo.com/image/cache/catalog/carlpoole/mtesitoo_20161002_120411919038420_1475424256-74x74.jpg","image":"http://tesitoo.com/image/cache/catalog/carlpoole/mtesitoo_20161002_120411919038420_1475424256-500x500.jpg"}],"price":"D0","tax":"D0","special":null,"discounts":[],"options":[],"manufacturer":null,"reward_points":0,"reward_points_needed_to_buy":0,"attribute_groups":[],"minimum_quantity":1,"stock_status":"In Stock","related_products":[],"rating":0,"reviews":"0 reviews","review_enabled":true,"recurrings":[],"vendor_id":"23","vendor_name":"CarlCompany","quantity":"100","status":"1"}}`

**Comment by david-r-edgar** [comment]
Hi @carlpoole I added the fields to the GET request in 1b0a2c7a1ae5c42f918735c81e7180ef83774cf4
Please check whether this is sufficient for what you need.

**Comment by carlpoole** [comment]
Cheers, I see them on the product details screen now. I am not showing them in the response for the product list, though. It looks like that request is the /product/vendor one. Could you add them there too?

**Comment by david-r-edgar** [comment]
I assume you mean /vendor/products rather than /product/vendor?
I added location and categories to that request's response. Is this OK? It didn't seem particularly relevant to add the length and weight class ids, given that the length and weight values aren't in the response.

**Comment by carlpoole** [comment]
Fixed in 9432354
