### ISSUE TITLE
Price should be a decimal, not an integer

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/mtesitoo-android#3]
Adding a new product, I found that I was unable to add a decimal price, just an integer.

(The value of the dalasi means that sometimes a decimal may be required, see eg. http://www.farmfresh.gm/en/home/92-fresh-parsely.html (and switch currency))

The limitation appears to be that the input page for the price is using `NumberFragment.java` where it specifies `TYPE_NUMBER_VARIATION_NORMAL`. Changing it to `TYPE_NUMBER_FLAG_DECIMAL` enabled decimals, but it's not correct to fix it like this since we want to keep other values - eg. the quantity - as integers.

**Comment by carlpoole** [comment]
Fixed in https://github.com/projectwife/mtesitoo-android/commit/0363be2fdfe0d5f6eee87f68f29fd649a55c73ac
