### ISSUE TITLE
Android App Quits Unexpectedly

### ISSUE THREAD

**Issue by carlpoole** [projectwife/mtesitoo-android#36]
Reproduction steps:  Open App, login, click Orders on the navigation menu, click back on the phone, the app quits.

**Comment by kaizen10** [comment]
This is not specific to the Orders menu. I can replicate the same behaviour using any other menu button (e.g Home, Profile, Info, ...). My guess is that the back button hasn't been implemented for fragments that reuses HomeActivity.

**Comment by kaizen10** [comment]
Fixed back navigation for fragments in HomeActivity.java
