### ISSUE TITLE
registration password shown in plain text + no 're-enter password' field

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/mtesitoo-android#44]
When I register on the app, the 'password' box is a single plain-text visible input field. Text completions are supplied.

Most apps would:
1. obscure the password with stars (possibly with a 'show' option)
2. request the password to be entered again for verification
3. not allow input device to provide text completions (to avoid risk of mistaken input)

Probably we should follow these practices, unless there's a good reason not to do so.

**Comment by carlpoole** [comment]
Currently implementing new registration page which will make this issue go away. Will update when complete! Thanks

**Comment by david-r-edgar** [comment]
Verified no longer an issue on latest released version.
