### ISSUE TITLE
Registration: trim leading & trailing whitespace

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/mtesitoo-android#50]
leading & trailing whitespace should be trimmed from the username, password, telephone number and email address

Emails containing whitespace should not be accepted.

**Comment by carlpoole** [comment]
Similar to https://github.com/projectwife/mtesitoo-android/issues/35
We need to do field validation on registration too.

**Comment by carlpoole** [comment]
Whitespace trimmed in 62d5167 and 97aa9a4 fix. Still todo more validation on registration

**Comment by david-r-edgar** [comment]
Confirmed that whitespace has been trimmed on the latest registration screen.
