### ISSUE TITLE
Product description showing HTML tags

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/mtesitoo-android#51]
In the details for 'Avocado' (Vendor 1), some html tags are shown in the description field.

**Comment by carlpoole** [comment]
Are they there in the API call? We dont do any checking of what content might be inside the fields currently. Is there an expected behavior for if someone has put HTML in there?

**Comment by david-r-edgar** [comment]
I'm seeing this being returned in the JSON for `/api/v1/product/product/77`:
`"description": "<p><br></p>",`

I think the expected behaviour from the point of view of the user is that the description will look the same on both the website and the app.

The product entry form on the web interface has a wysiwyg editor, and the description is saved as HTML with inline styles (apparently only if required).
It's probably lower priority to support HTML editing, but stripping the tags might be a good idea until that gets implemented.

**Comment by CraigBanach** [comment]
Fixed in pull request 66, html formatting should be shown when viewing description, however, when editing a product on mobile, formatting will not available.
