### ISSUE TITLE
"Where are you from" shows categories instead of countries

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/mtesitoo-android#60]
On new registration of a vendor, the very first dialog is normally expected to show a list of countries. But occasionally it shows a list of categories instead.

I've seen this happen several times now. On the most recent occasion, it happened when I had no network connection. But that might have been unrelated.

**Comment by david-r-edgar** [comment]
https://socialcoder.slack.com/files/david.r.edgar/F3JKK68EN/screenshot_2016-12-23-17-40-15.png

**Comment by carlpoole** [comment]
Tried with and without internet connection. Having trouble reproducing this one. Will keep an eye out

**Comment by carlpoole** [comment]
Updated requirements: remove this and just display regions for The Gambia for now

**Comment by ptyagicodecamp** [comment]
@david-r-edgar : yes, I'm getting categories (always) on emulator.

**Comment by carlpoole** [comment]
Currently implementing new registration page which will make this issue go away. Will update when complete! Thanks

**Comment by david-r-edgar** [comment]
Confirmed that new implementation of registration no longer has this problem.
