### ISSUE TITLE
The application registers a new user who does not accept the terms

### ISSUE THREAD

**Issue by mariana-mxp** [projectwife/mtesitoo-android#80]
Baseline version: 1.0.0
Setup:
- Model: Nexus 4
- Android version: 5.1.1

Pre-conditions: 
- The user has no accounts on tesitoo application.
- The user has tesitoo mobile application.

Steps to reproduce:

1. Start application on mobile in portrait mode.
2. The user select the option "NEW USER".
3. The application shows the country options.
4. The user select the country option.
5. The application asks for the user's name.
6. The user fills the user's name  and selects "NEXT" button.
7. The application asks the user's first name.
8. The user fills the user's first name and selects "NEXT" button.
9. The application asks the user's last name.
10. The user fills the user's last name and selects "NEXT" button.
11. The application asks the user's password.
12. The user fills the user's password and selects "NEXT" button.
13. The application asks the user's email.
14. The user fills the user's email and selects "NEXT" button.
15. The application asks the user's phone number.
16. The user fills the user's phone number and selects "NEXT" button.
17. The application asks the user's street name.
18. The user fills the user's street name  and selects "NEXT" button.
19. The application asks the user's city.
20. The user fills the user's city  and selects "NEXT" button.
21. The application asks the user's postcode.
22. The user fills the user's  postcode and selects "NEXT" button.
23. The application asks the user's zone.
24. The user fills the user's  zone and selects "NEXT" button.
25. The application asks to user agree all the terms.
26. The user select the option NO.

Actual behavior:
The application register the user. 

Expect behavior:
The application does not register the user.

Occur: 100% 
Number of executions: 1 

Other informations:
- User name: mxp

**Comment by mariana-mxp** [comment]
In Apr / 6 / 2017 version the issue does not happen.

**Comment by ptyagicodecamp** [comment]
Action item for Developer: 

- Try reproducing  issue on master branch
```
If (able to reproduce issue on master branch) {
    Branch out from master branch.
    Name branch <dev-initials>-<quick description about issue>
    Fix issue and Test
    Create a Pull request(PR) and send out for review
    Merge PR into master after Approval.
} else {
   Update this ticket with "Close and comment" that issue is no more reproducible. 
}
```

**Comment by gwenpowers** [comment]
This does not happen any longer.  If user does not click accept, they cannot register.  (However Terms and Conditions link not working. )
