### ISSUE TITLE
The user can not add a new product

### ISSUE THREAD

**Issue by mariana-mxp** [projectwife/mtesitoo-android#83]
Baseline version: Apr / 6 / 2017 version
Setup:
- Model: Nexus 4
- Android version: 5.1.1

Pre-conditions: 
- The user 1 has account on tesitoo application.

Steps to reproduce:

1. Start application.
2. The application shows the first screen.
3. Select the "ADD" option.

Actual behavior:
The ADD button can not be used because it is hidden (please see images).
The user can not add a new product.

Expect behavior:
The ADD button can be used because it is hidden.
The user can add a new product.

Occur: 100% 
Number of execution: 3

![screenshot_2017-04-06-23-15-32](https://cloud.githubusercontent.com/assets/17710268/24782966/eeadf612-1b1f-11e7-81ef-cbd2c56daaac.png)
![screenshot_2017-04-06-23-14-57](https://cloud.githubusercontent.com/assets/17710268/24782967/eeb08da0-1b1f-11e7-8f6d-1ea3f9a691d9.png)
![screenshot_2017-04-06-23-20-35](https://cloud.githubusercontent.com/assets/17710268/24782977/fd6561ae-1b1f-11e7-83cf-867cbf1b6ea0.png)

**Comment by ptyagicodecamp** [comment]
Fixed and Merged into master. Available in Play Store.
