### ISSUE TITLE
Add product button appears to have no effect

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/mtesitoo-android#84]
I tried adding a product. But the 'Add' button doesn't work. It gives visual feedback that it's been pressed. But the screen stays as is, with no errors and nothing else happening.

Each time, the error log produces a new log:
"04-07 12:39:16.146 1541-1805/system_process W/AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client"
I don't know if this is at all relevant.

Using current master (6790e31bb817beda9da1770de2e340fe5e8a1317).
Emulator: Nexus 7 (2012) Android 5.1

**Comment by ptyagicodecamp** [comment]
@david-r-edgar I tried this flow, and seems "ADD" button on Home screen's top-right corner opens screen to add new product. 
- Launched App
- Clicked on "Home" menu from navigation drawer.
- Clicked on "ADD" button at top right corner of home screen.
- New Add product screen appeared.

Are these the steps that you tried or something different ?

**Comment by david-r-edgar** [comment]
Ah, sorry, I probably didn't explain well enough.
That worked fine.
Then I filled in all the fields.
It was the Add button to submit the new product which then had no effect.

**Comment by ptyagicodecamp** [comment]
@david-r-edgar : Thanks ! I can reproduce now :)

**Comment by ptyagicodecamp** [comment]
@david-r-edgar : Found out that it's not really a bug, but "not yet implemented" empty code block :(

**Comment by david-r-edgar** [comment]
now appears fixed on `pt-bugfixes`

**Comment by ptyagicodecamp** [comment]
Merged into master.
