### ISSUE TITLE
No validation errors shown when user registration fields are incorrect

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/mtesitoo-android#85]
I tried to register a new user.
- I put in a non-valid email address (just three alphabetic characters).
- I filled in the other fields correctly.
- I clicked Register.
=> Nothing happened.

The Android Monitor showed the response coming back from the server:
```
04-07 14:47:43.409 24029-26047/com.tesitoo E/Volley: [358] BasicNetwork.performRequest: Unexpected response code 400 for https://tesitoo.com/api/v1//vendor/register
04-07 14:47:43.409 24029-24029/com.tesitoo E/REG_ERR: {"errors":[{"code":"parameter_error","message":"E-Mail Address does not appear to be valid!"}]}
```

But this error was not indicated to the user.

**Comment by ptyagicodecamp** [comment]
Fixed in https://github.com/projectwife/mtesitoo-android/pull/105

**Comment by david-r-edgar** [comment]
Verified fixed on deployed app.
