### ISSUE TITLE
After adding 4 pictures to a product, it's no longer possible to delete any

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/mtesitoo-android#93]
Normally in product edit mode, clicking on an image gives me a dialog with 'delete this image' and 'add an image' options.

But once we reach the product photo limit (4 images total), the dialog is no longer shown. Instead we see a message appear at the bottom of the screen telling us we can't upload any photos.

Instead, we should still allow the user to delete the image, and just prevent them adding a new image.

**Comment by ptyagicodecamp** [comment]
Fixed in https://github.com/projectwife/mtesitoo-android/pull/105

**Comment by ptyagicodecamp** [comment]
@david-r-edgar Could you confirm if this looks good at your end as well ?

**Comment by david-r-edgar** [comment]
I think it's fine, yes. A few of the other issues (#106, #107, #108) made fully testing it a bit tricky, but the right options seemed to come up in the dialog.

**Comment by ptyagicodecamp** [comment]
OK. closing this ticket as resolved for now .
