### ISSUE TITLE
Quantity Incorrect for New Product

### ISSUE THREAD

**Issue by JimPiquant** [projectwife/mtesitoo-android#98]
Added a new product, quantity 2.  Saved and then reviewed details, quantity is 100.

**Comment by david-r-edgar** [comment]
I retested, and also saw this.
- Upon initially adding the product, the server admin pages, using the API via postman and the database all correctly report quantity=2.
- But the view product and edit product screens on the app both show quantity=100. Upon editing (changing an unrelated field) and saving, the product quantity in the db was changed to 100.

**Comment by JimPiquant** [comment]
I testing this and it appeared to be working correctly when adding a product and edit as well.
