### ISSUE TITLE
Product disappears after editing.

### ISSUE THREAD

**Issue by JimPiquant** [projectwife/mtesitoo-android#99]
This isn't consistent but regularly the product is removed after I edit it.  Trying to find the exact steps for a repro.

**Comment by david-r-edgar** [comment]
Are you using the app from the play store?

It might well be that the change I made just a day or two ago on the Android side (to use a different API request) will fix this.
The expiration dates were (are) being set wrongly, and the old API request therefore didn't include those products.
With the new API request, ALL the vendor's products are included.

**Comment by JimPiquant** [comment]
Yes, updated this morning from the Play Store.

**Comment by ptyagicodecamp** [comment]
@JimPiquant : Could you try it again on latest APK in Play Store. I fixed an issue around expiry dates on client side, that might be a potential fix for what you're seeing.

**Comment by ptyagicodecamp** [comment]
should be fixed now in play store/master branch.
